# Generated by Django 5.1 on 2024-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgcdn', '0002_alter_imgmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
